spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_mvp_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 09062005
  jpa:
    hibernate:
      ddl-auto: update  # ??? validate/none/validate ?? ?????????????
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8081

app:
  jwt:
    secret: replace-with-very-secret-change-in-prod
    issuer: architecht-booking-api
    access-ttl-seconds: 3600

nats:
  url: nats://localhost:4222

availability-engine:
  host: localhost
  port: 50051
